# Generated by Django 2.2.2 on 2019-06-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190609_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='available',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='new',
        ),
    ]
