# Generated by Django 2.2.2 on 2019-06-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190609_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
