# Generated by Django 2.2.2 on 2019-06-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190609_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='merch',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
