# Generated by Django 2.2.2 on 2019-06-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('size', models.CharField(choices=[('small', 'SMALL'), ('medium', 'MEDIUM'), ('large', 'LARGE')], default='meduim', max_length=6)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping1', models.CharField(choices=[('cheese', 'CHEESE'), ('pepperon', 'PEPPERON'), ('dick', 'DICK'), ('ass', 'ASS'), ('meat', 'MEAT')], max_length=10)),
                ('topping2', models.CharField(choices=[('cheese', 'CHEESE'), ('pepperon', 'PEPPERON'), ('dick', 'DICK'), ('ass', 'ASS'), ('meat', 'MEAT')], max_length=10)),
                ('topping3', models.CharField(choices=[('cheese', 'CHEESE'), ('pepperon', 'PEPPERON'), ('dick', 'DICK'), ('ass', 'ASS'), ('meat', 'MEAT')], max_length=10)),
                ('topping4', models.CharField(choices=[('cheese', 'CHEESE'), ('pepperon', 'PEPPERON'), ('dick', 'DICK'), ('ass', 'ASS'), ('meat', 'MEAT')], max_length=10)),
                ('topping5', models.CharField(choices=[('cheese', 'CHEESE'), ('pepperon', 'PEPPERON'), ('dick', 'DICK'), ('ass', 'ASS'), ('meat', 'MEAT')], max_length=10)),
            ],
        ),
    ]
