# Generated by Django 2.2.2 on 2019-06-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='NULL', upload_to='images'),
        ),
    ]
