# Generated by Django 2.2.2 on 2019-06-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20190607_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='/images/pizza/placeholder.png', upload_to='images/pizza'),
        ),
    ]
