# Generated by Django 2.2.2 on 2019-06-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20190607_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.TextField(default='PizzaSauce'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
