# Generated by Django 2.2.2 on 2019-06-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20190607_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
