# Generated by Django 2.2.2 on 2019-06-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_delete_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
                ('description', models.TextField(default='PizzaSauce')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('available', models.BooleanField(default=True)),
                ('new', models.BooleanField(default=False)),
                ('image', models.ImageField(default='/images/pizza/placeholder.png', upload_to='images/pizza')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Category')),
            ],
            options={
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
