# Generated by Django 2.2.2 on 2019-06-09 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20190608_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Pizza',
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
                ('description', models.TextField(default='1000 Liter')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(default='/images/drinks/placeholder.png', upload_to='images/drinks')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Category')),
            ],
            options={
                'index_together': {('id', 'slug')},
            },
        ),
    ]
